-- Company.dbo.DEPARTMENT definition

-- Drop table

-- DROP TABLE Company.dbo.DEPARTMENT;

CREATE TABLE Company.dbo.DEPARTMENT (
	DNUMBER int NOT NULL,
	DNAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MGRSSN char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MGRSTARTDATE date NULL,
	CONSTRAINT PK__DEPARTME__F5A986063CAE74CB PRIMARY KEY (DNUMBER)
);


-- Company.dbo.DEPENDENT definition

-- Drop table

-- DROP TABLE Company.dbo.DEPENDENT;

CREATE TABLE Company.dbo.DEPENDENT (
	ESSN char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DEPENDENT_NAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SEX char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BDATE date NULL,
	RELATIONSHIP varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT PK__DEPENDEN__82CB958207BBBFB3 PRIMARY KEY (ESSN,DEPENDENT_NAME)
);


-- Company.dbo.DEPT_LOCATIONS definition

-- Drop table

-- DROP TABLE Company.dbo.DEPT_LOCATIONS;

CREATE TABLE Company.dbo.DEPT_LOCATIONS (
	DNUMBER int NOT NULL,
	DLOCATION varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT PK__DEPT_LOC__2F9748E05C72187B PRIMARY KEY (DNUMBER,DLOCATION)
);


-- Company.dbo.EMPLOYEE definition

-- Drop table

-- DROP TABLE Company.dbo.EMPLOYEE;

CREATE TABLE Company.dbo.EMPLOYEE (
	SSN char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FNAME varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LNAME varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	BDATE date NULL,
	ADDRESS varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SEX char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SALARY decimal(10,2) NULL,
	SUPERSSN char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DNO int NULL,
	CONSTRAINT PK__EMPLOYEE__CA1E8E3D5AAFC021 PRIMARY KEY (SSN)
);


-- Company.dbo.PROJECT definition

-- Drop table

-- DROP TABLE Company.dbo.PROJECT;

CREATE TABLE Company.dbo.PROJECT (
	PNUMBER int NOT NULL,
	PNAME varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PLOCATION varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DNUM int NULL,
	CONSTRAINT PK__PROJECT__EC4259AF8ACDA47D PRIMARY KEY (PNUMBER)
);


-- Company.dbo.WORKS_ON definition

-- Drop table

-- DROP TABLE Company.dbo.WORKS_ON;

CREATE TABLE Company.dbo.WORKS_ON (
	ESSN char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PNO int NOT NULL,
	HOURS decimal(5,2) NULL,
	CONSTRAINT PK__WORKS_ON__CF59EC30A9A84593 PRIMARY KEY (ESSN,PNO)
);


-- Company.dbo.DEPARTMENT foreign keys

ALTER TABLE Company.dbo.DEPARTMENT ADD CONSTRAINT FK__DEPARTMEN__MGRSS__3F466844 FOREIGN KEY (MGRSSN) REFERENCES Company.dbo.EMPLOYEE(SSN);


-- Company.dbo.DEPENDENT foreign keys

ALTER TABLE Company.dbo.DEPENDENT ADD CONSTRAINT FK__DEPENDENT__ESSN__4BAC3F29 FOREIGN KEY (ESSN) REFERENCES Company.dbo.EMPLOYEE(SSN);


-- Company.dbo.DEPT_LOCATIONS foreign keys

ALTER TABLE Company.dbo.DEPT_LOCATIONS ADD CONSTRAINT FK__DEPT_LOCA__DNUMB__4222D4EF FOREIGN KEY (DNUMBER) REFERENCES Company.dbo.DEPARTMENT(DNUMBER);


-- Company.dbo.EMPLOYEE foreign keys

ALTER TABLE Company.dbo.EMPLOYEE ADD CONSTRAINT FK__EMPLOYEE__DNO__3E52440B FOREIGN KEY (DNO) REFERENCES Company.dbo.DEPARTMENT(DNUMBER);
ALTER TABLE Company.dbo.EMPLOYEE ADD CONSTRAINT FK__EMPLOYEE__SUPERS__3D5E1FD2 FOREIGN KEY (SUPERSSN) REFERENCES Company.dbo.EMPLOYEE(SSN);


-- Company.dbo.PROJECT foreign keys

ALTER TABLE Company.dbo.PROJECT ADD CONSTRAINT FK__PROJECT__DNUM__44FF419A FOREIGN KEY (DNUM) REFERENCES Company.dbo.DEPARTMENT(DNUMBER);


-- Company.dbo.WORKS_ON foreign keys

ALTER TABLE Company.dbo.WORKS_ON ADD CONSTRAINT FK__WORKS_ON__ESSN__47DBAE45 FOREIGN KEY (ESSN) REFERENCES Company.dbo.EMPLOYEE(SSN);
ALTER TABLE Company.dbo.WORKS_ON ADD CONSTRAINT FK__WORKS_ON__PNO__48CFD27E FOREIGN KEY (PNO) REFERENCES Company.dbo.PROJECT(PNUMBER);