// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using EFCoreDay2.Models;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDay2.Context;

public partial class AirlineContext : DbContext
{
    public AirlineContext(DbContextOptions<AirlineContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Aircraft> Aircraft { get; set; }

    public virtual DbSet<Airline> Airlines { get; set; }

    public virtual DbSet<AirlinePhone> AirlinePhones { get; set; }

    public virtual DbSet<Assigned> Assigneds { get; set; }

    public virtual DbSet<Crew> Crews { get; set; }

    public virtual DbSet<CrewHostess> CrewHostesses { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeQualification> EmployeeQualifications { get; set; }

    public virtual DbSet<Route> Routes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aircraft>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Aircraft__3214EC277C057F1E");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.AirlineId).HasColumnName("AirlineID");
            entity.Property(e => e.Mode)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Airline).WithMany(p => p.Aircraft)
                .HasForeignKey(d => d.AirlineId)
                .HasConstraintName("FK__Aircraft__Airlin__49C3F6B7");
        });

        modelBuilder.Entity<Airline>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Airline__3214EC279FE0363C");

            entity.ToTable("Airline");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Address)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ContactPerson)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<AirlinePhone>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Airline_Phone");

            entity.Property(e => e.AirlineId).HasColumnName("AirlineID");
            entity.Property(e => e.Phone)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.HasOne(d => d.Airline).WithMany()
                .HasForeignKey(d => d.AirlineId)
                .HasConstraintName("FK__Airline_P__Airli__3F466844");
        });

        modelBuilder.Entity<Assigned>(entity =>
        {
            entity.HasKey(e => new { e.AircraftId, e.RouteId, e.DeptDateTime }).HasName("PK__Assigned__B8AE88A16306701B");

            entity.ToTable("Assigned");

            entity.Property(e => e.AircraftId).HasColumnName("AircraftID");
            entity.Property(e => e.RouteId).HasColumnName("RouteID");
            entity.Property(e => e.DeptDateTime).HasColumnType("datetime");
            entity.Property(e => e.ArrDateTime).HasColumnType("datetime");

            entity.HasOne(d => d.Aircraft).WithMany(p => p.Assigneds)
                .HasForeignKey(d => d.AircraftId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Assigned__Aircra__5441852A");

            entity.HasOne(d => d.Route).WithMany(p => p.Assigneds)
                .HasForeignKey(d => d.RouteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Assigned__RouteI__5535A963");
        });

        modelBuilder.Entity<Crew>(entity =>
        {
            entity.HasKey(e => e.CrewId).HasName("PK__Crew__89BCFC09EB76C6E6");

            entity.ToTable("Crew");

            entity.HasIndex(e => e.AircraftId, "UQ__Crew__F75CBC0AE54267D1").IsUnique();

            entity.Property(e => e.CrewId)
                .ValueGeneratedNever()
                .HasColumnName("CrewID");
            entity.Property(e => e.AircraftId).HasColumnName("AircraftID");
            entity.Property(e => e.AssPilot)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FirstHostess)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MainPilot)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Aircraft).WithOne(p => p.Crew)
                .HasForeignKey<Crew>(d => d.AircraftId)
                .HasConstraintName("FK__Crew__AircraftID__4D94879B");
        });

        modelBuilder.Entity<CrewHostess>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Crew_Hostess");

            entity.Property(e => e.CrewId).HasColumnName("CrewID");
            entity.Property(e => e.HostessName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Crew).WithMany()
                .HasForeignKey(d => d.CrewId)
                .HasConstraintName("FK__Crew_Host__CrewI__4F7CD00D");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC2719C05D24");

            entity.ToTable("Employee");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Address)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.AirlineId).HasColumnName("AirlineID");
            entity.Property(e => e.Bday).HasColumnName("BDay");
            entity.Property(e => e.Bmonth).HasColumnName("BMonth");
            entity.Property(e => e.Byear).HasColumnName("BYear");
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Position)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.HasOne(d => d.Airline).WithMany(p => p.Employees)
                .HasForeignKey(d => d.AirlineId)
                .HasConstraintName("FK__Employee__Airlin__4222D4EF");
        });

        modelBuilder.Entity<EmployeeQualification>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("Employee_Qualification");

            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.Qualification)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Employee).WithMany()
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK__Employee___Emplo__440B1D61");
        });

        modelBuilder.Entity<Route>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Route__3214EC27732A8E04");

            entity.ToTable("Route");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Classification)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Destination)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Origin)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}