// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EFCoreDay2.Models;

public partial class Aircraft
{
    public int Id { get; set; }

    public int? Capacity { get; set; }

    public string? Mode { get; set; }

    public int? AirlineId { get; set; }

    public virtual Airline? Airline { get; set; }

    public virtual ICollection<Assigned> Assigneds { get; set; } = new List<Assigned>();

    public virtual Crew? Crew { get; set; }
}