// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EFCoreDay2.Models;

public partial class AirlinePhone
{
    public int? AirlineId { get; set; }

    public string? Phone { get; set; }

    public virtual Airline? Airline { get; set; }
}