// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EFCoreDay2.Models;

public partial class Assigned
{
    public int AircraftId { get; set; }

    public int RouteId { get; set; }

    public DateTime DeptDateTime { get; set; }

    public DateTime? ArrDateTime { get; set; }

    public int? PassengerNum { get; set; }

    public virtual Aircraft Aircraft { get; set; } = null!;

    public virtual Route Route { get; set; } = null!;
}