// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EFCoreDay2.Models;

public partial class Crew
{
    public int CrewId { get; set; }

    public string? MainPilot { get; set; }

    public string? AssPilot { get; set; }

    public string? FirstHostess { get; set; }

    public int? AircraftId { get; set; }

    public virtual Aircraft? Aircraft { get; set; }
}