// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EFCoreDay2.Models;

public partial class CrewHostess
{
    public int? CrewId { get; set; }

    public string? HostessName { get; set; }

    public virtual Crew? Crew { get; set; }
}