// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EFCoreDay2.Models;

public partial class EmployeeQualification
{
    public int? EmployeeId { get; set; }

    public string? Qualification { get; set; }

    public virtual Employee? Employee { get; set; }
}