// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EFCoreDay2.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Address { get; set; }

    public int? Bday { get; set; }

    public int? Bmonth { get; set; }

    public int? Byear { get; set; }

    public string? Position { get; set; }

    public string? Gender { get; set; }

    public int? AirlineId { get; set; }

    public virtual Airline? Airline { get; set; }
}