// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EFCoreDay2.Models;

public partial class Route
{
    public int Id { get; set; }

    public string? Origin { get; set; }

    public string? Destination { get; set; }

    public string? Classification { get; set; }

    public int? Distance { get; set; }

    public virtual ICollection<Assigned> Assigneds { get; set; } = new List<Assigned>();
}